### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by sergiocorreia** [matthieugomez/benchmark-stata-r#1]
Hi Matthieu,

Is it possible to add -collapse- to the benchmarks?
Probably two versions, one when collapsing to a small unit (e.g. individual -> country) and one for larger unit (e.g. individual -> household).

I think it's one of the most common Stata commands and would be interesting to see its performance (I have the gut feeling that it will be quite slow, even with the -fast- option).

**Comment by matthieugomez** [comment]
I just added 2 collapse commands. thanks.

**Comment by matthieugomez** [comment]
I'm now using `fcollapse` & `fegen group`.

**Comment by sergiocorreia** [comment]
Cool!

By the way, it *might* be a good idea to have some separate benchmarks for collapse/merges depending on whether the keys are string or not.  I tend to avoid strings as much as possible (take too much space), so (at least for me) collapses by strings are not the most common use case.

**Comment by sergiocorreia** [comment]
Also, could you try with the Github version of reghdfe? It should be a up to 3x faster depending on how many FEs are there

**Comment by matthieugomez** [comment]
Updating reghdfe made it 10x faster. Well done!

**Comment by sergiocorreia** [comment]
Thanks! BTW, it's actually faster than areg/xtreg for 1 FE, so it might be interesting to use it then.

Also, I fixed the -quiet- on fmerge/join

**Comment by matthieugomez** [comment]
I've added `fmerge` and `reghdfe` in the latest commit
https://github.com/matthieugomez/benchmark-stata-r/commit/9b507122019eab30ea3468e2117b62333507bcda

Actually, I made a mistake in my first `reghdfe` timing — the 
final result is that you're now approximately as fast as `lfe` which is still pretty impressive.
`fmerge` is 3x faster for int matching. However, it is slower than`merge` for strings matching.

**Comment by sergiocorreia** [comment]
Yep, 3x is closer to what I remember. If the internal of ftools get rewritten to C, there would be a 4x speedup on top of that (as well as for every command in ftools) but C is not my expertise.

Interesting about fmerge. I'll see if I'm missing anything optimization, else I'll just call merge if I detect that the variables are strings.

**Comment by matthieugomez** [comment]
Same thing with `fegen = group` actually. Compared to `egen`, it is much faster with ints, much slower with strings.

**Comment by sergiocorreia** [comment]
Interesting. I know that for small ints ftools is fast, but for large numbers or strings it calls hash1(), so I don't know yet if the difference is just because of hash1() or because of something else with strings.
