### ISSUE TITLE
Misleading time function for R multicore operations?

### ISSUE THREAD

**Issue by grantmcdermott** [matthieugomez/benchmark-stata-r#10]
Hi Matthieu,

In the [benchmark-r.r](https://github.com/matthieugomez/benchmark-stata-r/blob/master/code/2-benchmark-r.r) file you define the timing function as

```r
time <- function(x){sum(system.time(x)[1:2])}
```

So, you're essentially summing the "user" (first) and system"  (second) columns of `system.time()`. However, because "user" CPU time accumulates time spent across cores, aren't you essentially punishing any multicore operation? 

I mean, maybe I'm missing something obvious &mdash; or it has to do with equating against StataMP's timing functions &mdash; but why not simply take the "elapsed" (third) column of `system.time()`?

A probably redundant reprex:

``` r
library(fst)
library(fixest)
library(microbenchmark)

setFixest_nthreads(4)

DT <- read.fst("~/statabenchmark/1e7.fst") 
DT1 <- DT[1:(nrow(DT)/2),]

reg_2hfe <- function() invisible(feols(v3 ~  v2 + id4 + id5  + as.factor(v1) | id6 + id3, DT1))

## time function
time <- function(x){sum(system.time(x)[1:2])}
time(reg_2hfe())
#> [1] 31.89

## full system.time output (for comparison)
system.time(reg_2hfe())
#>    user  system elapsed 
#>  30.445   0.911   9.410

## microbenchmark (another comparison)
microbenchmark(reg_2hfe(), times = 5)
#> Unit: seconds
#>        expr      min       lq     mean   median       uq      max neval
#>  reg_2hfe() 9.540085 9.590495 9.669584 9.638338 9.692307 9.886695     5
```

<sup>Created on 2020-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by matthieugomez** [comment]
I am not sure why I did this. I definitely did not realize it accumulated time across cores. Could you do a pull request?

**Comment by matthieugomez** [comment]
Never mind I've done it. https://github.com/matthieugomez/benchmark-stata-r/commit/4b34de23fcbe035229e7d8794344d081ccbc3f6c
