### ISSUE TITLE
remarks to 3-benchmark-stata.do

### ISSUE THREAD

**Issue by rwalke** [matthieugomez/benchmark-stata-r#13]
Hi,
Thanks for your code.
Just two remarks:
I think it would help if you add
ssc install autorename
ssc install ftools
into the comment section as well.

To make it directly usable on Stata SE
/* benchmark */
if `c(processors)' >= 2 set processors 2
would help.

Best wishes,
Rainer

**Comment by matthieugomez** [comment]
Thanks!
