### ISSUE TITLE
Data.Table class is not equivalent to a Stata data set

### ISSUE THREAD

**Issue by wbuchanan** [matthieugomez/benchmark-stata-r#2]
Can you use R-base functionality to compare against Stata core functionality?  Creating a primary key in the two data.tables isn't really comparable to doing the same in Stata.

**Comment by matthieugomez** [comment]
Comparing R base and Stata core is not the goal of this benchmark.

**Comment by wbuchanan** [comment]
Then what exactly is the goal when you are comparing the two platforms?  I think that using fastxtile and other user written commands is also inherently wrong.  More importantly, however, is that people are using your results without any understanding of the implications of your tests and the biases that exist in the timing results.  Not being explicit about these things doesn't help to improve any dialog and instead causes people to fire off blindly based on comparisons that are not wel documented, described, or understood by the third parties using the results.

**Comment by matthieugomez** [comment]
The goal is to compare the most performant commands in each language. I have added this caveat  [here](https://github.com/matthieugomez/benchmark-stata-r/commit/9a30922ddfd619b7f43910ea5f7f0a0b1760a77c)

**Comment by floswald** [comment]
makes complete sense to me to do this comparison this way, and I think this benchmark is great resource. Users are always going to want to use the fastest available command, and why would they not? If there is a better way to do those operations in Stata/R, please let us know.
