### ISSUE TITLE
Time merging from file on Disk

### ISSUE THREAD

**Issue by wbuchanan** [matthieugomez/benchmark-stata-r#3]
Stata only represents a single data set in memory at any given time, so comparing its performance (which is IO bound by nature) to joins of objects stored in RAM is not comparable.

**Comment by matthieugomez** [comment]
There is indeed a lot of commands where Stata uses IO where R does not :  `merge`, `collapse`, `reshape` and more generally every command that includes a `preserve`.  
Now, the goal of this benchmark is to compare the speed of the whole command from a user perspective. The fact that Stata commands use a lot of I/O operations means that the whole command is slower, even with the same underlying algorithm.

**Comment by wbuchanan** [comment]
That's fine, but it is not made clear whether your comparisons are timing based or RAM/memory management benchmarks.  In the case of this issue, R will always out perform because the implementation of merging a second option does not require an I/O operation.  This fundamentally biases the results vs comparing the time it takes to complete comparable actions.
