### ISSUE TITLE
Include fst package and missing values

### ISSUE THREAD

**Issue by HughParsonage** [matthieugomez/benchmark-stata-r#5]
Thanks for this repo: this is an illuminating benchmark. 

I was wondering whether you could consider updating the binary IO in R with the relatively recent `fst` package:  https://github.com/fstpackage/fst  -- though you may want to wait until `data.table` 1.10.6 which has very very fast csv reading. 

Also, I think you should consider adding in missing values (`NA`, `NaN`) in one of the data sets.

**Comment by matthieugomez** [comment]
Thanks, these are great suggestions.

**Comment by matthieugomez** [comment]
I am now using `fst`.
It seems that `fst` is as fast as Stata to write binary files, but significantly slower to read them (for 500Mo file, 0.5sec in Stata vs 5sec in fst).

**Comment by matthieugomez** [comment]
This may interest @MarcusKlik

**Comment by MarcusKlik** [comment]
Thanks for including the `fst` package, those benchmarks are definitely very interesting! Your measured speed of 100 Mb /s for `fst` reading speeds seems a little slow. In my experience, the slowest reads are those of character columns but those are significantly faster than that. I'll run the benchmarks and get back to you on that. It might be nice to include the development version of `fst`. It has a multi threaded core and usually maxes out the SSD in both writing and reading.

Good work!

**Comment by matthieugomez** [comment]
Thanks, and thanks for the `fst` package. I have just tried the development version of `fst` but I don't think my installation is using OpenMP for some reason.
```R
fst 0.7.3 IN DEVELOPMENT built 2017-07-07 19:11:10 UTC
(OpenMP was not detected, using single threaded mode)
```

**Comment by MarcusKlik** [comment]
Hi @matthieugomez, that would probably mean that you are on OS X ? Currently, OpenMP is not supported by default on Mac, and `data.table` suffers the same problem. A workaround is documented on the `data.table` [installation pages](https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac). But even without OpenMP, your benchmark should run faster,

(I also noticed that half your columns are character columns and I didn't implement OpenMP for them yet. They are the hardest to parallelize due to the global string pool used in R.)

Anyway, will  get back to you on the benchmarks!

**Comment by MarcusKlik** [comment]
Hi @matthieugomez and @HughParsonage, I've written a small benchmark script which tests writing and reading your specific dataset. The speeds on my system (modest laptop using 4  cores but with fast NVME SSD) are around 1 GB/s. The comparison with Stata is tricky however, because Stata uses a completely different memory model than R. For example, R uses a global string pool to store elements from a character vector, which means reading and writing such a vector needs a lot of memory look-ups and is relatively slow. I have no idea how Stata manages it's character vector, but perhaps it's more efficient, so your benchmark might be comparing more 'language efficiency' than serialization speeds, but perhaps that was your intent!

The script:


``` r

# To run the script, download the relevant packages:
# devtools::install_github("Rdatatable/data.table")
# devtools::install_github("fstpackage/fst", ref = "develop")
# install.packages("microbenchmark")

library(data.table)
library(fst)
library(microbenchmark)

K <- 100
N <- 1e7L
set.seed(1)

dt <- data.frame(
  id1 = sample(sprintf("id%03d",1:K), N, TRUE),         # large groups (char)
  id2 = sample(sprintf("id%03d",1:K), N, TRUE),         # large groups (char)
  id3 = sample(sprintf("id%010d",1:(N/K)), N, TRUE),    # small groups (char)
  id4 = sample(K, N, TRUE),                             # large groups (int)
  id5 = sample(K, N, TRUE),                             # large groups (int)
  id6 = sample(N/K, N, TRUE),                           # small groups (int)
  v1 =  sample(5, N, TRUE),                             # int in range [1,5]
  v2 =  sample(1e6, N, TRUE),                           # int in range [1,1e6]
  v3 =  sample(round(runif(100,max = 100), 4), N, TRUE) # numeric e.g. 23.5749
)


# Writing benchmark
saveRDS("warmup disk", "warmup.rds")  # get SSD out of it's sleep

# Run each benchmark only once to avoid SSD caching (gets you unrealisticly high speeds)
time_write <- microbenchmark(
  fstwrite(dt, "test.fst"),
  times = 1
)

time_read <- microbenchmark(
  x <- fstread("test.fst"),
  times = 1
)


# Get speed from benchmark and object size
SpeedFromBench <- function(time, size)
{
  dt_size <- as.numeric(size)  # table size in bytes
  1e3 * dt_size / time  # write speed in MB /s
}

SpeedFromBench(time_write$time, object.size(dt))  # write speed (MB/s)
#> [1] 956.4028

SpeedFromBench(time_read$time, object.size(dt))  # read speed (MB/s)
#> [1] 1594.597
```

**Comment by matthieugomez** [comment]
Thanks @MarcusKlik for the benchmark. FYI, on my computer, I obtain 
```R
SpeedFromBench(time_write$time, object.size(dt))  # write speed (MB/s)
#> [1] 191.3599
SpeedFromBench(time_read$time, object.size(dt))  # read speed (MB/s)
#> [1] 403.4278
```
It corresponds to a reading time of 0.9s, which is now only two times slower than Stata.

That being said, I still obtain a reading time of 3.4s if I use the option `stringsAsFactors = FALSE` when constructing the dataframe (which is the default for data.tables and tibbles)

```R
f <- function(AreStringFactors){
   K <- 100
   N <- 1e7L
   dt <- data.frame(
     id1 = sample(sprintf("id%03d",1:K), N, TRUE),         # large groups (char)
     id2 = sample(sprintf("id%03d",1:K), N, TRUE),         # large groups (char)
     id3 = sample(sprintf("id%010d",1:(N/K)), N, TRUE),    # small groups (char)
     id4 = sample(K, N, TRUE),                             # large groups (int)
     id5 = sample(K, N, TRUE),                             # large groups (int)
     id6 = sample(N/K, N, TRUE),                           # small groups (int)
     v1 =  sample(5, N, TRUE),                             # int in range [1,5]
     v2 =  sample(1e6, N, TRUE),                           # int in range [1,1e6]
     v3 =  sample(round(runif(100,max = 100), 4), N, TRUE), # numeric e.g. 23.5749
     stringsAsFactors = AreStringFactors
   )
   fstwrite(dt, "test.fst")
   sum(system.time(x <- fstread("test.fst"))[1:2])
}

f(TRUE)
#> [1] 0.911
f(FALSE)
#> [1] 3.438
```

**Comment by matthieugomez** [comment]
@MarcusKlik and of course you are totally right: I am only testing the speed of the overall command from the user perspective — this is not a comparison of the pure serialization speed.

**Comment by MarcusKlik** [comment]
Hi @matthieugomez, indeed, non-factors are much slower! `R` really suffers from the global string pool, you can see the same effect with `feather` for example (see below). It's a good push for me to start implementing the multi-threaded reader and writer for character columns in `fst` 👍 .

Do you have any idea how Stata implements the character vectors internally? Is it factoring the strings automatically?

``` r

# To run the script, download the relevant packages:
# devtools::install_github("Rdatatable/data.table")
# devtools::install_github("fstpackage/fst", ref = "develop")
# install.packages("microbenchmark")

library(data.table)
library(fst)
library(feather)
library(microbenchmark)

f <- function(writer, reader, AreStringFactors = TRUE){
  K <- 100
  N <- 1e7L

  dt <- data.frame(
    id1 = sample(sprintf("id%03d",1:K), N, TRUE),         # large groups (char)
    id2 = sample(sprintf("id%03d",1:K), N, TRUE),         # large groups (char)
    id3 = sample(sprintf("id%010d",1:(N/K)), N, TRUE),    # small groups (char)
    id4 = sample(K, N, TRUE),                             # large groups (int)
    id5 = sample(K, N, TRUE),                             # large groups (int)
    id6 = sample(N/K, N, TRUE),                           # small groups (int)
    v1 =  sample(5, N, TRUE),                             # int in range [1,5]
    v2 =  sample(1e6, N, TRUE),                           # int in range [1,1e6]
    v3 =  sample(round(runif(100,max = 100), 4), N, TRUE), # numeric e.g. 23.5749
    stringsAsFactors = AreStringFactors
  )
  
  # benchmark
  saveRDS("warmup disk", "warmup.rds")  # get SSD out of it's sleep

  res_write <- microbenchmark(
    writer(dt, "test.fst"),
    times = 1
  )
  
  res_read <- microbenchmark(
    reader("test.fst"),
    times = 1
  )

  data.table(Write = 1e-9 * res_write$time, read = 1e-9 * res_read$time)
}


# feather
f(write_feather, read_feather)
#>       Write      read
#> 1: 1.078978 0.3182886
f(write_feather, read_feather, FALSE)
#>       Write     read
#> 1: 2.855196 3.220406

# fst
f(fstwrite, fstread)
#>        Write      read
#> 1: 0.4670294 0.2550093
f(fstwrite, fstread, FALSE)
#>       Write     read
#> 1: 1.504204 3.364586
```

**Comment by matthieugomez** [comment]
Thanks @MarcusKlik !

I don't really know how Stata implements the character vectors internally. That being said, if I create a new character vector by repeating a character vectors 10 times, the new vector uses 10 times the space of the initial vector. So this suggests that there is no string pool in Stata, right? 

Now, I am still going to compare the two in my benchmark, since a string variable in Stata corresponds to a character vector in R from a user perspective. As you say, it is a speed test of the joint (R, fst) rather than a speed test of fst.

Thanks again for your package and for your comments here.

**Comment by MarcusKlik** [comment]
Good deduction :-) I guess Stata has a faster basic implementation on character vectors than R. 

And good luck with your benchmarks, please let me know if you need anything specific with your benchmarks on `fst`. I'm planning a extensive benchmark suite to compare `fst` with other serialization methods in R (see also [this issue](https://github.com/fstpackage/fst/issues/5) and [this issue](https://github.com/fstpackage/fst/issues/48)), perhaps it would be interesting to run a comparable benchmark for Stata as well when it's finished?
