### ISSUE TITLE
sreshape

### ISSUE THREAD

**Issue by Danferno** [matthieugomez/benchmark-stata-r#7]
Hi

have you tried using sreshape instead of stata's default reshape? In my particular application it was 10x faster than the default.

PS: I wrote a single-line timing function called timeit a while back, it essentially wraps timer on/timer off. This may or may not be more convenient than the tic/toc you use.

**Comment by matthieugomez** [comment]
Hi,
I'm now using `fastreshape`: https://github.com/mdroste/stata-fastreshape
I could not install sreshape from SSC
